version: '3'
networks:
  producao-local:
    driver: bridge
services:
    mysqldb:
      image: mysql
      container_name: mysqldb
      ports:
        - "3306:3306"
      networks:
        - producao-local
      environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root

    mongodb:
      image: mongo
      container_name: mongodb
      networks:
        - producao-local
      ports:
      - 27017:27017
